### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by miccjing** [YeomanYe/web-scripts#7]
谷歌打开下一页也会打开新标签，这样一会儿就会有很多个，
建议实现自动加载下一页并拼接

**Comment by YeomanYe** [comment]
你说的效果建议使用这个脚本：
https://greasyfork.org/zh-TW/scripts/14178-ac-baidu-%E9%87%8D%E5%AE%9A%E5%90%91%E4%BC%98%E5%8C%96%E7%99%BE%E5%BA%A6%E6%90%9C%E7%8B%97%E8%B0%B7%E6%AD%8C%E5%BF%85%E5%BA%94%E6%90%9C%E7%B4%A2-favicon-%E5%8F%8C%E5%88%97
